model: yolov5s-cls.pt
data: imagenette160
epochs: 10
batch_size: 64
imgsz: 224
nosave: false
cache: null
device: ''
workers: 8
project: "../../../../../\uB300\uD559\uAD50/\uAC15\uC758\uAD00\uB828/4-1/yolov55/yolo-gesture-detection/yolov5/runs/train-cls"
name: exp
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: "../../../../../\uB300\uD559\uAD50/\uAC15\uC758\uAD00\uB828/4-1/yolov55/yolo-gesture-detection/yolov5/runs/train-cls/exp2"
